config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'tasks/show'

  get 'tasks/new'

  get 'tasks/edit'

  get 'store', to:'pages#store'

  get 'about', to:'pages#about'

  get 'checkout', to:'pages#checkout'

  resources :inventories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:product, :price, :quantity, :exp_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def store
  end

  def about
  end

  def checkout
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
  	@task = Task.new
  end

  def edit
  end

  def create
  	@taks = Taks.new(task_params)

  	respond_to do |format|
  		if @task.save
  			format.html { redirect_to @task, notice: "Task was created successfully!"}
  			format.json { render :show, status: :created, location: @task }
  		else
  			format.html { render :new }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
		respond_to do |format|
  		if @task.update(task_params)
  			format.html { redirect_to @task, notice: "Task was updated successfully!"}
  			format.json { render :show, status: :created, location: @task }
  		else
  			format.html { render :new }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@task.destroy
  	respond_to do |format|
  		format.html { redirect_to project_url(@task.project_id), notice: "Task was deleted successfully!"}
  			format.json { head :no_content }
  	end
  end

  private

  	def set_task
  		@task = Task.find(params[:id])
		end

  	def task_params
  		params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
		end
  	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/inventories/_form.html.erb
<%= form_for(inventory) do |f| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %>
    <%= f.text_field :product %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :exp_date %>
    <%= f.date_select :exp_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Exp date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.product %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.quantity %></td>
        <td><%= inventory.exp_date %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @inventory.product %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<p>
  <strong>Exp date:</strong>
  <%= @inventory.exp_date %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  	<%= render "shared/nav" %>

  	
  
  	<%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/checkout.html.erb
<h1>Checkout</h1>

app/views/pages/home.html.erb
<h1>The home page</h1>

<div class='bull'>
	<ul>
		<li>Skateboards</li>
		<li>Skateboard Supplies</li>
		<li>All your skateboard stuff</li>
	</ul>
</div>

<div id="pricingtable">
	<div class="package">
		<h2>Deck Only</h2>
		<p>All decks from major brands, with the best prices around.</p>
		<p>$29.99 - $49.99</p>
	</div>

	<div class="package">
		<h2>Complete Set Up</h2>
		<p>Get a complete skateboard set up, fully customizable deck, trucks, wheels, and bearings.</p>
		<p>$99.99 - $149.99</p>
	</div>

	<div class="package">
		<h2>Various Hardware</h2>
		<p>Pick up standalone hardware: wheels, trucks, bearings etc.</p>
		<p>$9.99 - $39.99</p>
	</div>
</div>

app/views/pages/store.html.erb
<h1>Store</h1>

app/views/shared/_nav.html.erb
<div id="nav">
	<span class="navbar"><%= link_to "Home", root_path %></span>
	<span class="navbar"><%= link_to "Store", store_path %></span>
  	<span class="navbar"><%= link_to "About", about_path %></span>
  	<span class="navbar"><%= link_to "Checkout", checkout_path %></span>
</div>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>